# Site settings
title: Wyann blog
email: wyann22@gmail.com
description: Shity CODE
baseurl: "" # the subpath of your site, e.g. /blo
url: "https://wyann22.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:wyann22

# Build settings
markdown: kramdown
